### ISSUE TITLE
CONFIGURATION parameter has not been configured in web.xml

### ISSUE THREAD

**Issue by kulkarniamit** [itszero/docker-opengrok#9]
Executed:
`docker run -d -v /home/alice/src:/src -p 80:8080 itszero/opengrok`

I just entered a search term `main` in Symbol text box and clicked on "Search"
Result from: 
`http://localhost/source/search?q=&defs=&refs=main&path=&hist=&type=c`

**There was an error!**
## CONFIGURATION parameter has not been configured in web.xml! Please configure your webapp.

`dataRoot` parameter is not set in configuration.xml!

```
java.security.InvalidParameterException: dataRoot parameter is not set in configuration.xml!
	at org.opensolaris.opengrok.web.PageConfig.getDataRoot(PageConfig.java:1155)
	at org.opensolaris.opengrok.web.PageConfig.prepareSearch(PageConfig.java:1180)
	at org.apache.jsp.search_jsp._jspService(search_jsp.java:179)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:442)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1083)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:640)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

Host Machine:
```
$ cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core)
$ docker -v
Docker version 18.03.1-ce, build 9ee9f40
```

**Comment by kulkarniamit** [comment]
My bad, I just needed to wait some time before clicking Search.
I was indexing a large project with thousands of files.
The issue resolved after allowing it to index for some time.
